### ISSUE TITLE
License

### ISSUE THREAD

**Issue by chrzyki** [ganeshjawahar/ner-rnn#1]
Thank you very much for making your deep learning NLP projects available, @ganeshjawahar! Your code has been very helpful for getting my own deep learning endeavours underway.

I'm raising this issue because I've been wondering whether it'd be possible for you to add some kind of license to your repositories. If I'm not mistaken, the current 'licenselessness' means that you and only you are allowed to distribute/reproduce/use your code. Of course, if this was your original intention then please just ignore my ramblings. :) If not, it would be super awesome if you could add some kind of licensing information.

If I can help with any of that, I'd be more than happy to do so!

**Comment by ganeshjawahar** [comment]
Thanks for pointing it out. I have added the MIT License file to all the projects. Please let me know if that's sufficient.

**Comment by chrzyki** [comment]
That is perfectly sufficient and very awesome! Thank you very much!
